FROM ubuntu:24.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends iproute2 tcpdump python3 iputils-ping perl ca-certificates && rm -rf /var/lib/apt/lists/*
